# Service sets motion mode for MD devices

uint16[] device_ids # Device IDs
string[] mode       # "IMPEDANCE", "POSITION_PID", "POSITION_PROFILE", "VELOCITY_PID", "RAW_TORQUE"
---
bool[] success      # Success status for each device
