#pragma once
#include <string>

struct candleParams_S
{
    std::string bus;
    std::string data_rate;
    std::string default_qos;
    std::string joint_name_prefix;
    double      gripper_open_position_rad;
    double      gripper_closed_position_rad;
    double      gripper_impedance_kp;
    double      gripper_impedance_kd;
    double      gripper_velocity_limit_rad_s;
    double      gripper_torque_limit_nm;
    double      soft_close_fast_torque_limit_nm;
    double      soft_close_slow_torque_limit_nm;
    double      soft_close_profile_acceleration_rad_s2;
    double      soft_close_profile_deceleration_rad_s2;
    double      soft_close_closed_tol_rad;
    int         soft_close_fast_duration_ms;
    int         health_publish_period_ms;
    double      encoder_wrap_period_rad;
    double      position_recovery_max_delta_rad;
    int         position_recovery_samples;
    int         position_recovery_retry_ms;
    std::string startup_position_policy;
    std::string position_state_file;
    int         position_state_write_period_ms;
    double      position_state_min_change_rad;
    std::string homing_direction_by_id;
    double      homing_torque_nm;
    double      homing_second_pass_torque_nm;
    double      homing_stop_verification_torque_nm;
    int         homing_stop_verification_ramp_ms;
    int         homing_torque_ramp_ms;
    double      homing_velocity_trip_rad_s;
    double      homing_min_bus_voltage_v;
    double      homing_stall_velocity_rad_s;
    int         homing_stall_dwell_ms;
    double      homing_max_travel_rad;
    int         homing_timeout_ms;
    double      homing_backoff_rad;
    double      homing_repeatability_rad;
    double      homing_min_motion_rad;
    bool        init_devices_zero;
};
